### PR TITLE
added timestampTz support

### PR DESCRIPTION
**Pull request by FranPregernik**
At my company we are using timestampTz and it was missing so I added it.

### CODE REVIEW

**Comment by yajra** [comment]
@FranPregernik, thanks for this PR but I think Laravel does not officially support timestamp with time zone which is why the test is failing... http://laravel.com/docs/5.1/migrations#creating-columns

Anyways, since I think this is needed on real world app then I think it's ok to merge your request. Just fix the tests please. Also, you might need to update the `OracleBlueprint` and include this method as well. See test results for details https://travis-ci.org/yajra/laravel-oci8/jobs/91399201. Thanks!

```php
PHP Fatal error:  Call to undefined method yajra\Oci8\Schema\OracleBlueprint::timestampsTz()
```

**Comment by FranPregernik** [comment]
I added this test and this test is passing on my machine (such a cliche).

The reason why I think this is not the issue with the missing timestampsTz method is because your OracleBlueprint extends from Illuminate\Database\Schema\Blueprint which has a public timestampsTz method.

I created a Cloud9 workspace just to test it out and also there the two tests I added pass:
```
franpregernik:~/workspace/laravel-oci8 (develop) $ vendor/bin/phpunit --debug
PHPUnit 4.0.20 by Sebastian Bergmann.

Configuration read from /home/ubuntu/workspace/laravel-oci8/phpunit.xml


Starting test 'DatabaseConnectionTest::testCreateSequence'.
.
Starting test 'DatabaseConnectionTest::testCreateSequenceInvalidName'.
.
Starting test 'DatabaseConnectionTest::testDropSequence'.
.
Starting test 'DatabaseConnectionTest::testDropSequenceInvalidName'.
.
Starting test 'DatabaseConnectorTest::testCreateConnection'.
.
Starting test 'DatabaseConnectorTest::testOptionResolution'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #0 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234))(ADDRESS = (PROTOCOL = TCP)(HOST = oracle.host)(PORT = 1234)) (LOAD_BALANCE = yes) (FAILOVER = on) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ORCL)))', array('oracle', 'localhost, oracle.host', '1234', 'ORCL', ''))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #1 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234))(ADDRESS = (PROTOCOL = TCP)(HOST = oracle.host)(PORT = 1234)) (LOAD_BALANCE = yes) (FAILOVER = on) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ORCL)))', array('oracle', 'localhost, oracle.host', '1234', 'ORCL', '', 'users'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #2 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234)) (CONNECT_DATA =(SID = ORCL)))', array('oracle', 'localhost', '1234', 'ORCL', ''))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #3 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234)) (CONNECT_DATA =(SID = ORCL)))', array('oci8', 'localhost', '1234', 'ORCL', ''))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #4 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234)) (CONNECT_DATA =(SID = ORCL)))', array('pdo-via-oci8', 'localhost', '1234', 'ORCL', ''))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #5 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234)) (CONNECT_DATA =(SERVICE_NAME = SID_ALIAS)))', array('oracle', 'localhost', '1234', '', '', 'SID_ALIAS'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #6 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234)) (CONNECT_DATA =(SERVICE_NAME = SID_ALIAS)))', array('oci8', 'localhost', '1234', '', '', 'SID_ALIAS'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #7 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1234)) (CONNECT_DATA =(SERVICE_NAME = SID_ALIAS)))', array('pdo-via-oci8', 'localhost', '1234', '', '', 'SID_ALIAS'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #8 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 4321)) (CONNECT_DATA =(SID = ORCL)))', array('oracle', '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 4321)) (CONNECT_DATA =(SID = ORCL)))'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #9 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 4321)) (CONNECT_DATA =(SID = ORCL)))', array('oci8', '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 4321)) (CONNECT_DATA =(SID = ORCL)))'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #10 ('(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 4321)) (CONNECT_DATA =(SID = ORCL)))', array('pdo-via-oci8', '(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 4321)) (CONNECT_DATA =(SID = ORCL)))'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #11 ('xe', array('oracle', 'xe'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #12 ('xe', array('oci8', 'xe'))'.
.
Starting test 'DatabaseConnectorTest::testOracleConnectCallsCreateConnectionWithProperArguments with data set #13 ('xe', array('pdo-via-oci8', 'xe'))'.
.
Starting test 'Oci8QueryBuilderTest::testBasicSelect'.
.
Starting test 'Oci8QueryBuilderTest::testAddingSelects'.
.
Starting test 'Oci8QueryBuilderTest::testBasicSelectWithPrefix'.
.
Starting test 'Oci8QueryBuilderTest::testBasicSelectDistinct'.
.
Starting test 'Oci8QueryBuilderTest::testBasicAlias'.
.
Starting test 'Oci8QueryBuilderTest::testBasicTableWrapping'.
.
Starting test 'Oci8QueryBuilderTest::testBasicWheres'.
.
Starting test 'Oci8QueryBuilderTest::testWhereBetweens'.
.
Starting test 'Oci8QueryBuilderTest::testBasicOrWheres'.
.
Starting test 'Oci8QueryBuilderTest::testRawWheres'.
.
Starting test 'Oci8QueryBuilderTest::testRawOrWheres'.
.
Starting test 'Oci8QueryBuilderTest::testBasicWhereIns'.
.
Starting test 'Oci8QueryBuilderTest::testBasicWhereNotIns'.
.
Starting test 'Oci8QueryBuilderTest::testUnions'.
.
Starting test 'Oci8QueryBuilderTest::testUnionAlls'.
.
Starting test 'Oci8QueryBuilderTest::testMultipleUnions'.
.
Starting test 'Oci8QueryBuilderTest::testMultipleUnionAlls'.
.
Starting test 'Oci8QueryBuilderTest::testSubSelectWhereIns'.
.
Starting test 'Oci8QueryBuilderTest::testBasicWhereNulls'.
.
Starting test 'Oci8QueryBuilderTest::testBasicWhereNotNulls'.
.
Starting test 'Oci8QueryBuilderTest::testGroupBys'.
.
Starting test 'Oci8QueryBuilderTest::testOrderBys'.
.
Starting test 'Oci8QueryBuilderTest::testHavings'.
.
Starting test 'Oci8QueryBuilderTest::testRawHavings'.
.
Starting test 'Oci8QueryBuilderTest::testLimitsAndOffsets'.
.
Starting test 'Oci8QueryBuilderTest::testWhereShortcut'.
.
Starting test 'Oci8QueryBuilderTest::testNestedWheres'.
.
Starting test 'Oci8QueryBuilderTest::testFullSubSelects'.
.
Starting test 'Oci8QueryBuilderTest::testWhereExists'.
.
Starting test 'Oci8QueryBuilderTest::testBasicJoins'.
.
Starting test 'Oci8QueryBuilderTest::testComplexJoin'.
.
Starting test 'Oci8QueryBuilderTest::testRawExpressionsInSelect'.
.
Starting test 'Oci8QueryBuilderTest::testFindReturnsFirstResultByID'.
.
Starting test 'Oci8QueryBuilderTest::testFirstMethodReturnsFirstResult'.
.
Starting test 'Oci8QueryBuilderTest::testListMethodsGetsArrayOfColumnValues'.
.
Starting test 'Oci8QueryBuilderTest::testImplode'.
.
Starting test 'Oci8QueryBuilderTest::testPluckMethodReturnsSingleColumn'.
.
Starting test 'Oci8QueryBuilderTest::testAggregateCountFunction'.
.
Starting test 'Oci8QueryBuilderTest::testAggregateExistsFunction'.
E
Starting test 'Oci8QueryBuilderTest::testAggregateMaxFunction'.
.
Starting test 'Oci8QueryBuilderTest::testAggregateMinFunction'.
.
Starting test 'Oci8QueryBuilderTest::testAggregateSumFunction'.
.
Starting test 'Oci8QueryBuilderTest::testInsertMethod'.
.  63 / 144 ( 43%)

Starting test 'Oci8QueryBuilderTest::testMultipleInsertMethod'.
.
Starting test 'Oci8QueryBuilderTest::testInsertGetIdMethod'.
.
Starting test 'Oci8QueryBuilderTest::testInsertLobMethod'.
.
Starting test 'Oci8QueryBuilderTest::testInsertOnlyLobMethod'.
.
Starting test 'Oci8QueryBuilderTest::testUpdateLobMethod'.
.
Starting test 'Oci8QueryBuilderTest::testUpdateOnlyLobMethod'.
.
Starting test 'Oci8QueryBuilderTest::testInsertGetIdMethodRemovesExpressions'.
.
Starting test 'Oci8QueryBuilderTest::testInsertMethodRespectsRawBindings'.
.
Starting test 'Oci8QueryBuilderTest::testUpdateMethod'.
.
Starting test 'Oci8QueryBuilderTest::testUpdateMethodWithJoins'.
.
Starting test 'Oci8QueryBuilderTest::testUpdateMethodRespectsRaw'.
.
Starting test 'Oci8QueryBuilderTest::testDeleteMethod'.
.
Starting test 'Oci8QueryBuilderTest::testTruncateMethod'.
.
Starting test 'Oci8QueryBuilderTest::testMergeWheresCanMergeWheresAndBindings'.
.
Starting test 'Oci8QueryBuilderTest::testProvidingNullOrFalseAsSecondParameterBuildsCorrectly'.
.
Starting test 'Oci8QueryBuilderTest::testDynamicWhere'.
.
Starting test 'Oci8QueryBuilderTest::testDynamicWhereIsNotGreedy'.
.
Starting test 'Oci8QueryBuilderTest::testCallTriggersDynamicWhere'.
.
Starting test 'Oci8QueryBuilderTest::testBuilderThrowsExpectedExceptionWithUndefinedMethod'.
.
Starting test 'Oci8QueryBuilderTest::testOracleLock'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTable'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithPrimary'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithPrimaryAndForeignKeys'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithDefaultValueAndIsNotNull'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithPrefix'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithPrefixAndPrimary'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithPrefixPrimaryAndForeignKeys'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicCreateTableWithPrefixPrimaryAndForeignKeysWithCascadeDelete'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicAlterTable'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicAlterTableWithPrimary'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicAlterTableWithPrefix'.
.
Starting test 'Oci8SchemaGrammarTest::testBasicAlterTableWithPrefixAndPrimary'.
.
Starting test 'Oci8SchemaGrammarTest::testDropTable'.
.
Starting test 'Oci8SchemaGrammarTest::testCompileTableExistsMethod'.
.
Starting test 'Oci8SchemaGrammarTest::testCompileColumnExistsMethod'.
.
Starting test 'Oci8SchemaGrammarTest::testDropTableWithPrefix'.
.
Starting test 'Oci8SchemaGrammarTest::testDropColumn'.
.
Starting test 'Oci8SchemaGrammarTest::testDropPrimary'.
.
Starting test 'Oci8SchemaGrammarTest::testDropUnique'.
.
Starting test 'Oci8SchemaGrammarTest::testDropIndex'.
.
Starting test 'Oci8SchemaGrammarTest::testDropForeign'.
.
Starting test 'Oci8SchemaGrammarTest::testDropTimestamps'.
.
Starting test 'Oci8SchemaGrammarTest::testRenameTable'.
.
Starting test 'Oci8SchemaGrammarTest::testRenameTableWithPrefix'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingPrimaryKey'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingPrimaryKeyWithConstraintAutomaticName'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingPrimaryKeyWithConstraintAutomaticNameGreaterThanThirtyCharacters'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingUniqueKey'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingDefinedUniqueKeyWithPrefix'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingGeneratedUniqueKeyWithPrefix'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingIndex'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingForeignKey'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingForeignKeyWithCascadeDelete'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingIncrementingID'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingString'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingLongText'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingMediumText'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingText'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingChar'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingBigInteger'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingInteger'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingMediumInteger'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingSmallInteger'.
. 126 / 144 ( 87%)

Starting test 'Oci8SchemaGrammarTest::testAddingTinyInteger'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingFloat'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingDouble'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingDecimal'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingBoolean'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingEnum'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingEnumWithDefaultValue'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingDate'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingDateTime'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingTime'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingTimeStamp'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingTimeStampTz'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingNullableTimeStamps'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingTimeStamps'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingTimeStampTzs'.
.
Starting test 'Oci8SchemaGrammarTest::testAddingBinary'.
.
Starting test 'SequenceTest::it_will_create_sequence'.
.
Starting test 'SequenceTest::it_will_drop_sequence'.
.

Time: 396 ms, Memory: 10.50Mb

There was 1 error:

1) Oci8QueryBuilderTest::testAggregateExistsFunction
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_3_Illuminate_Database_ConnectionInterface::select("select exists(select * from users) as exists", array(), true). Either the method was unexpected or its arguments matched no expected argument list for this method



/home/ubuntu/workspace/laravel-oci8/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/home/ubuntu/workspace/laravel-oci8/vendor/illuminate/database/Query/Builder.php:1617
/home/ubuntu/workspace/laravel-oci8/tests/Oci8QueryBuilderTest.php:543
                                       
FAILURES!                              
```

The only thing failing for me, which was failing even before I did any commits was Oci8QueryBuilderTest::testAggregateExistsFunction.

Am I missing something obvious here?

**Comment by FranPregernik** [comment]
Added!

I was missing the fact that timestampTz was added in 5.1.
Travis/composer pulls the 5.0.33 version in php 5.4 build.

**Comment by yajra** [comment]
Thanks, I wasn't aware that timestampsTz was already available on 5.1 ^_^.

For the aggregate function test, it's been quite a while since the package was updated. There may have been some changes on the framework that makes the test fail. Will do some tests on my side later and then merge this. Thanks!

**Comment by yajra** [comment]
One thing, do you think this will not break Laravel 4 installations? The package for L4 & L5 both uses v2.x. Maybe I should make a new Tag v3.x specifically for Laravel 5++ installations and drop support for PHP5.4... Hmm...

**Comment by FranPregernik** [comment]
IMHO I would split L4 and L5.

**Comment by yajra** [comment]
@FranPregernik, yeah. Just realized that I have to split the versions as it is becoming hard to maintain. >.<
I will be doing some work for the version 3 release and this will be included on version 3 instead. 

For the aggregate issue, I think this is indeed related to the update on framework and had open a new issue to track it. Thanks!

**Comment by yajra** [comment]
I just released your PR on v2.4.4. Version 3 might take some time and you might this feature now. Thanks!

**Comment by FranPregernik** [comment]
@yajra Thank you!

**Pull request merged**
