### PR TITLE
[5.4] Refactor executeFunction like procedure.

### PR DESCRIPTION
**Pull request by ardani**
i read code  executeFunction, it call still using params in name function
i create pull request for make it simple call like executeProcedure and change name variable to make it readable

### CODE REVIEW

**Comment by yajra** [comment]
👍  thanks! Will review and test this when I got the chance!

**Comment by mstaack** [comment]
great! but we still need to take care of different respone types..array..cursor etc

**Comment by ardani** [comment]
Nice catch Max, i think need custom type for result

**Comment by mstaack** [comment]
like response types of  `TYPE ref_cursor IS REF CURSOR;` as an example

**Comment by ardani** [comment]
```php
public function executeProcedure($procedureName, array $bindings = [], $returnType = PDO::PARAM_STMT)
```
i check again, this function already support for returnType default return type is `cursor`
so if we want return in different type can return type to `PARAM_LOB`
http://php.net/manual/en/pdo.constants.php

**Comment by mstaack** [comment]
we need some tests for this...for sure

**Comment by mstaack** [comment]
@ardani have you worked on this lately?  i am also  again at a point where i need to execute crazy procedures  :)

**Comment by mstaack** [comment]
started to work on this here https://github.com/yajra/laravel-oci8/tree/execute-procedure
 will keep you updated ..still need to clean a lot :D

**Comment by mstaack** [comment]
closing this in favor of https://github.com/yajra/laravel-oci8/pull/319

**Pull request closed without merging**
