### PR TITLE
[5.5] Do not wrap numeric values. Fix #346.

### LINKED ISSUE #346: Issue with laravel 5.3+ (int -> string in Grammar)
This issue is more laravel-related, but maybe you can avoid it by extending some laravel classes...
So:

When joining some oracle table with raw numeric value, Laravel, starting from 5.3, mutates integer value into string. Oracle throws an ORA-00904 (invalid identifier) error.

### Code snippet of problem

```php
$query->join('SOMETABLE', function($join){
    $join->on('SOMETABLE.A', '=', 'BASETABLE.B');
    $join->on('SOMETABLE.B', '=', 123456);  # <---- here is the problem
});
```

Error Message : ORA-00904: "50136901": invalid identifier

### details

The problem is in Query\Builder::toSql() -> Database\Grammar::wrap( $value, $prefixAlias = false )

The wrap() result is always string, even if integer given.

The simple way is to patch it with something like " if( is_int($value) ) return $value "

### PR DESCRIPTION
**Pull request by ircop**
avoid wrap() stringify integers, fix #346

### CODE REVIEW

**Comment by yajra** [comment]
Looks good but need to run some tests on actual app to make sure this does not break anything. Thanks!

**Comment by yajra** [comment]
Btw, you mentioned you are using 5.3? The PR is targeted on 5.5 branch.

**Comment by ircop** [comment]
I've updated to 5.5 (issue still exists), and this patch is for 5.5

**Comment by mstaack** [comment]
Looks ok for me

**Comment by yajra** [comment]
Released on v5.5.2, thanks!

**Comment by ircop** [comment]
Thank you!

**Pull request merged**
