### PR TITLE
Fix Error Message : ORA-00936: missing expression. Case when array is…

### PR DESCRIPTION
**Pull request by djob**
… empty

### CODE REVIEW

**Comment by yajra** [comment]
Is it possible to provide a snippet to replicate the error this is fixing? I checked `Illuminate\Database\Query\Grammars\Grammar` and it's implementing the same checking.

```php
    /**
     * Compile a select query into SQL.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return string
     */
    public function compileSelect(Builder $query)
    {
        if (is_null($query->columns)) {
            $query->columns = ['*'];
        }

        return trim($this->concatenate($this->compileComponents($query)));
    }
```

**Comment by djob** [comment]
Problem appears when argument provided to Model::all() is empty array.
e.g
```php
class Repository {
    public function all(array $columns = [])
    {
        return $this->model->all($columns);
    }
}
```

And yes, Laravel has same error as result. (mysql tested)

**Comment by yajra** [comment]
Maybe you should set the default value of columns to `['*']` instead?

Anyways, this seems valid but there might be some reason behind the framework why they use `is_null` instead of `empty`? Can you try making a PR on the framework and lets get their opinion? This might really be a bug as you have replicated it on mysql.

**Comment by yajra** [comment]
I think the reason behind this is there are cases where some users use [`select 0 ...`](http://stackoverflow.com/questions/13219472/why-select-0-instead-of-select) and `empty(0) == true`.

**Pull request closed without merging**
