### PR TITLE
[7.x] Remove table alias in run pagination count query with group.

### PR DESCRIPTION
**Pull request by deandex**

### CODE REVIEW

**Comment by yajra** [comment]
Can you please provide a sample query that the PR fixes? The code looks good. Thanks!

**Comment by yajra** [comment]
Created PR #615 which is a duplicate on this PR for Laravel 8. I also added some tests that were extracted from the framework. However, I think a test case is missing for this specific issue.  Can you please provide the query so that I can also add the test or I'm just missing something? Thanks!

**Comment by deandex** [comment]
I use my current project query to test it with group and join table query, not sure it will suitable with your test.

My query like this :
Select a.site_name, a.client_name, b.product_code, max(b.product_name) as product_name, sum(quantity) as quantity, sum(quantity_in) as quantity_in, sum(quantity_out) as quantity_out From table_a as a left join table_b as b On a.client = b.client Group By a.site_name, a.client_name, b.product_code

**Comment by yajra** [comment]
Released on v7.0.2 🚀 Thanks!

**Comment by deandex** [comment]
Wow cool.. Thanks @yajra :sunglasses:

**Comment by yajra** [comment]
I also just released v7.1.0 and applied all the fixes done on v8. Found several issues but already captured it on unit tests including this. Thanks!

**Pull request merged**
