### PR TITLE
Add oracle prefix schema

### PR DESCRIPTION
**Pull request by mfrancois**
I need to make the schema prefix before the table name :

````sql
SELECT * FROM MySchema.PROFILE WHERE 1;
```

I need to add MySchema. To do this I create  a new method `withSchemaPrefix ` and it called in `withTablePrefix `.

I create a new config to ` 'prefix_schema' => env('DB_SCHEMA_PREFIX', ''),`

Regards,
Maxime

### CODE REVIEW

**Comment by yajra** [comment]
Thanks @mfrancois, will review this PR as soon as I can.

**Comment by yajra** [comment]
Released on v5.2.1. Thanks a lot!

**Comment by ChaosPower** [comment]
Thanks! This will now allow automated schema calls to other users' tables. 
```
select * from user1.table
```

**Comment by mohd-aidi** [comment]
hi, can you merge this commit to version 5.1 too?

**Pull request merged**
