### PR TITLE
Overwrite Try Again Method of Parent Class

### PR DESCRIPTION
**Pull request by Stoffo**
While testing the reconnect logic, we noticed that we still get reconnect errors from the db. This PR should fix this issue.

### CODE REVIEW

**Comment by yajra** [comment]
@Stoffo I think the issue on your last PR was due to trait method override. As per review, `causedByLostConnection` is inherited from `trait DetectsLostConnections`. Hence, `parent::causedByLostConnection($e))` is not valid since it's not a class method? Maybe a better solution would be something like below?

```php
class Oci8Connection extends Connection
{
    use DetectsLostConnections {
        causedByLostConnection as protected traitCausedByLostConnection;
    }
...
    public function causedByLostConnection(Exception $e)
    {
        if ($this->traitCausedByLostConnection($e)) {
            return true;
        }
...
```

**Comment by yajra** [comment]
BTW, I just noticed that `causedByLostConnection` should have a visibility of `protected` and not `public`?

```php
trait DetectsLostConnections
{
    /**
     * Determine if the given exception was caused by a lost connection.
     *
     * @param  \Exception  $e
     * @return bool
     */
    protected function causedByLostConnection(Exception $e)
```

**Comment by Stoffo** [comment]
Hi @yajra, i fixed the public flag, that was a mistake. I tested the logic to overwrite the trait and it is working fine so far.

**Comment by yajra** [comment]
@Stoffo it seems like `tryAgainIfCausedByLostConnection` is exactly the same with the parent class so I guess it's not needed to overwrite it?

**Comment by Stoffo** [comment]
Yeah you're right, I will close this PR then.

**Pull request closed without merging**
