### PR TITLE
[5.4] Add oci8 dependency for composer.

### PR DESCRIPTION
**Pull request by mstaack**
this should warn users that their extension is missing! we have a lot of the same issues regarding missing oci8 extension

### CODE REVIEW

**Comment by mstaack** [comment]
@yajra should we add oci8 installation like here:
https://github.com/jpina/oci8/blob/master/.travis.yml#L25

?

looks nice

**Comment by yajra** [comment]
Is it `php-oci8` or `ext-oci8`? Like on this [code](https://github.com/jpina/oci8/blob/master/composer.json#L16)?

**Comment by mstaack** [comment]
sure thing its ext ;)

**Comment by mstaack** [comment]
looks better now..
`The requested PHP extension ext-oci8 >=2.0.0 is missing from your system. Install or enable PHP's oci8 extension.`

now we need to add docker-oracle with oci8 ;)

**Comment by mstaack** [comment]
adding oracle via docker + installing oci8 extension will of course add some stuff/complexity to this package...for now i fixed the tests by ignoring the extension req... this should be fine for now

**Comment by yajra** [comment]
Released on v5.4.5. Thanks for this great idea. I guess this will help lessen the same issue over and over. 👍

**Pull request merged**
