### PR TITLE
[5.6] Better way to shorten the index name.

### PR DESCRIPTION
**Pull request by OmarAta**
this way it is less likely to have an index name conflict

### CODE REVIEW

**Comment by yajra** [comment]
Need to review this one further. Have to check also if it will affect when dropping the indexes manually. AFAIK, there is a convention that laravel follows and we have to review it too.

**Comment by yajra** [comment]
I just tested this with Laravel Passport with known index name issue and seems to work well now. Doing some testing but I think this is good to go. ❤️

**Comment by yajra** [comment]
- Fix #273 
- Fix #336

**Comment by OmarAta** [comment]
That's good to hear. Thanks 😃 👍

**Pull request merged**
