### PR TITLE
[8.x] Add PHP8 support.

### PR DESCRIPTION
**Pull request by yajra**
Requires https://github.com/yajra/pdo-via-oci8/pull/83
Fix https://github.com/yajra/laravel-oci8/issues/624

### CODE REVIEW

**Comment by dionysiosarvanitis** [comment]
So far no problems.

**Comment by yajra** [comment]
@dionysiosarvanitis thanks for the review. Can't tests on actual projects as I cannot upgrade to PHP8 yet.

Do you think we can released this PR?

**Review by OmarHossamEldin — COMMENTED** [review]
LGTM

**Comment by dionysiosarvanitis** [comment]
Yes, seems stable to me.

**Comment by yajra** [comment]
Released on v8.3.0 🚀  Thanks!

**Comment by dionysiosarvanitis** [comment]
Great! Thanks a lot!

**Pull request merged**
