### PR TITLE
fix: lock for update implementation

### LINKED ISSUE #819: lock/lockForUpdate locks up all rows even combined with limit (Job Queue becomes unusable on large table)
Currently, when you create an SQL query with a limit, it gets translated into the following SQL like this:

```php
\DB::table('laraveljobs')->first();
```
becomes:
```sql
select * from ( select * from laraveljobs ) where rownum = 1;
```

When you now add a lock request, I would expect the lock to be applied only on the limited rows. However, due to the execution order of the statement, the nested select gets executed first, including the lock request, locking up the full table before returning the first row.

```php
\DB::table('laraveljobs')->lockForUpdate()->first();
```
becomes

```sql
select * from ( select * from laraveljobs for update ) where rownum = 1;
```

This behaviour kinda breaks the laravel database queue worker for a large pool of job entries. Our job table accumulated 40.000 jobs, but now the SQL statement of the laravel job worker takes almost 4 minutes to finish because it requests locks for all the rows instead of just for the first.

The code for getting the next job can be found in the Laravel Framework here: https://github.com/illuminate/queue/blob/master/DatabaseQueue.php#L236

```php
    protected function getNextAvailableJob($queue)
    {
        $job = $this->database->table($this->table)
                    ->lock($this->getLockForPopping())
                    ->where('queue', $this->getQueue($queue))
                    ->where(function ($query) {
                        $this->isAvailable($query);
                        $this->isReservedButExpired($query);
                    })
                    ->orderBy('id', 'asc')
                    ->first();

        return $job ? new DatabaseJobRecord((object) $job) : null;
    }
```

I think the solution would be to make the lock part of the constraint parameter of compileTableExpression in OracleGrammar.php to add it behind the limit. Do you have an idea how to solve this issue?

https://github.com/yajra/laravel-oci8/blob/10.x/src/Oci8/Query/Grammars/OracleGrammar.php#L178

### PR DESCRIPTION
**Pull request by yajra**
fix: #819
fix: `forPage` SQL
fix: `compileSavepointRollBack`

### CODE REVIEW

**Comment by yajra** [comment]
Requesting for review @Zazama, Thanks!

**Comment by yajra** [comment]
I tested this on one of my actual projects and seems to work fine. Will merge next week, in case anyone wants to review.

BTW, are you using queue via database driver? I tested using horizon.

**Comment by Zazama** [comment]
Yeah, we're using the default database driver (CLI only) for some of our job queues 👍

**Comment by jbstowe** [comment]
@yajra I wanted to mention this change is causing the following oracle error for us in the latest Laravel 10 release when using the database queue driver:

ORA-02014: cannot select FOR UPDATE from view with DISTINCT, GROUP BY, etc.

Query being executed:

`select * from (select * from JOBS where QUEUE = 'default' and ((RESERVED_AT is null and AVAILABLE_AT <= '1709136694') or (RESERVED_AT <= '1709136694')) order by ID asc) where rownum = 1 for update;  `

Downgrading to 10.4.2 resolves the issue, also removing the `order by ID asc` resolves it but I am guessing Laravel itself is generating that sql. It is also possible our oracle DB version is incompatible somehow. If you can think of any items local to our laravel project to check just let me know.

Thanks!

**Comment by yajra** [comment]
It seems like removing or putting the order clause at the end works fine. Will try to adjust the builder.

```sql
select *
from (select *
      from JOBS
      where QUEUE = 'default'
        and ((RESERVED_AT is null and AVAILABLE_AT <= '1709347756') or (RESERVED_AT <= '1709347756'))
      )
where rownum = 1 for update
order by ID asc;
```

**Comment by yajra** [comment]
@jbstowe patched release on v10.4.4, please confirm. Thanks!

**Comment by jbstowe** [comment]
@yajra This is working for us now, thank you!

**Pull request merged**
