### PR TITLE
Table and column comments

### PR DESCRIPTION
**Pull request by rafael-renan-pacheco**
When creating a table:
```php
Schema::create('flights', function (Blueprint $table) {
    $table->increments('id');
    $table->string('name')->comment('Flight name'); /* Column comment */
    $table->string('airline')->comment('Airline name'); /* Column comment */

    $table->comment = 'Flights table'; /* Table comment */
});
```

When modifying a table:
```php
Schema::table('flights', function ($table) {
    $table->comment = 'A flights table'; /* Table comment */

    $table->commentColumns = [
        'name' => 'This is the flight name', /* Column comment */
        'airline' => 'This is the airline name' /* Column comment */
    ];
});
```

### CODE REVIEW

**Comment by yajra** [comment]
@rafael-renan-pacheco, this is great :100: !!! Just tested it and works like a charm. Thanks! Will fix the failing pluck test and will released this asap. :+1:

**Comment by yajra** [comment]
One thing though, the implementation will fail on other database because `comment()` method does not exists on parent Builder class. Maybe we should try something that will not break when we switch from Oracle to MySQL? What do you think? 

Maybe we should also use the approach done on MySQL? 
```php
$table->string('product_name')->comment = "Product name column";
$table->comment = "table comment";
```

Nonetheless, I really :heart:  this PR but let us think if we should care for other DB too. ^_^

**Comment by yajra** [comment]
FYI: This is the error I received when I switch from Oracle to MySQL using Laravel 5.2
```php
 [Symfony\Component\Debug\Exception\FatalThrowableError]                                
  Fatal error: Call to undefined method Illuminate\Database\Schema\Blueprint::comment()  
```

**Comment by yajra** [comment]
The code below works well.
```php
$table->string('product_name')->comment = "Product name column";
// and
$table->string('product_name')->comment("Product name column");
```
This one breaks the switching.
```php
$table->comment("table comment");
```

So maybe using `$table->comment = "table comment";` would be safer to use?

**Comment by rafael-renan-pacheco** [comment]
Hi @yajra!

Did some changes to it, can you try in MySQL to see if works?

I didn't find how to change comments on MySQL, so I created a new one with `$table->commentColumns`

**Comment by yajra** [comment]
Perfect :100: !!! Will be released on v4.1.0.

**Pull request merged**
